// <auto-generated />
using System;
using FreightAccounting.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FreightAccounting.Core.Migrations
{
    [DbContext(typeof(FreightAccountingContext))]
    [Migration("20230828123142_UserTableAdded")]
    partial class UserTableAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FreightAccounting.Core.Entities.Debtor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DebtAmount")
                        .HasColumnType("int");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Debtors");
                });

            modelBuilder.Entity("FreightAccounting.Core.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExpensesAmount")
                        .HasColumnType("int");

                    b.Property<int>("Income")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("FreightAccounting.Core.Entities.OperatorUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OperatorUsers");
                });

            modelBuilder.Entity("FreightAccounting.Core.Entities.Remittance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InsurancePayment")
                        .HasColumnType("int");

                    b.Property<int>("NetProfit")
                        .HasColumnType("int");

                    b.Property<int>("OperatorUserId")
                        .HasColumnType("int");

                    b.Property<int>("OrganizationPayment")
                        .HasColumnType("int");

                    b.Property<string>("ProductInsuranceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceviedCommission")
                        .HasColumnType("int");

                    b.Property<string>("RemittanceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubmittedUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaxPayment")
                        .HasColumnType("int");

                    b.Property<int>("TransforPayment")
                        .HasColumnType("int");

                    b.Property<int>("UserCut")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OperatorUserId");

                    b.ToTable("Remittances");
                });

            modelBuilder.Entity("FreightAccounting.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameAndFamily")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameAndFamily = "root",
                            Password = "113765b146867037b814a8ef1c2ec35d73bfb77c8d27a5f1a520099f5949cfaa",
                            Username = "root"
                        });
                });

            modelBuilder.Entity("FreightAccounting.Core.Entities.Remittance", b =>
                {
                    b.HasOne("FreightAccounting.Core.Entities.OperatorUser", "OperatorUser")
                        .WithMany("Remittances")
                        .HasForeignKey("OperatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperatorUser");
                });

            modelBuilder.Entity("FreightAccounting.Core.Entities.OperatorUser", b =>
                {
                    b.Navigation("Remittances");
                });
#pragma warning restore 612, 618
        }
    }
}
